apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: harbor-library
        namespace: flux-system
      version: "35.0.0"
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
#    defaultRules:
#      rules:
#        kubeScheduler: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.fc277073030.com
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.fc277073030.com
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.fc277073030.com