apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  releaseName: eck-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: harbor-library
        namespace: flux-system
      version: "2.1.0"
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace